// ─── Mock Issues ─────────────────────────────────────────────────────────────
export const MOCK_ISSUES = [
  {
    id: 'issue_001',
    title: 'Deep Pothole Causing Accidents — Avinashi Road',
    description: 'Approximately 2m wide, 30cm deep pothole near Ganesh Theatre junction. Multiple bikes have fallen this week. Night visibility is zero. Urgent repair needed before monsoon.',
    category: 'pothole',
    categoryLabel: 'Road & Infrastructure',
    severity: 'critical',
    status: 'verified',
    votes: 147,
    verifications: 8,
    userVoted: null,
    userVerified: false,
    emoji: '🕳️',
    location: {
      lat: 11.0168, lng: 77.0282,
      address: 'Avinashi Road, near Ganesh Theatre, Coimbatore',
      ward: 'Ward 12',
      zone: 'North Zone',
    },
    reporter: { id:'user_002', name:'Arjun Kumar', initials:'AK', level:12 },
    assignedDept: 'PWD Coimbatore',
    workOrder: 'PWD-2024-8821',
    aiAnalysis: {
      category: 'pothole',
      severity: 'critical',
      confidence: 0.94,
      tags: ['Pothole','High Severity','Road Risk','Night Hazard','2m Diameter'],
      estimatedCost: 8500,
      similarIssues: 3,
    },
    images: ['/demo/pothole1.jpg'],
    comments: [
      { id:'c1', user:'Priya V.', text:'Confirmed! Nearly fell here yesterday.', time:'1h ago' },
      { id:'c2', user:'Muthu S.', text:'PWD should be notified immediately.', time:'45m ago' },
    ],
    timeline: [
      { status:'Reported', time:'Jun 22, 9:14 AM', done:true },
      { status:'AI Verified', time:'Jun 22, 9:15 AM', done:true, note:'Classified: Pothole · Critical' },
      { status:'Community Validated', time:'Jun 22, 11:30 AM', done:true, note:'3 neighbors confirmed' },
      { status:'Assigned to PWD', time:'Jun 23, 2:00 PM', done:true, note:'Work order #PWD-2024-8821' },
      { status:'Resolution Pending', time:'ETA: Jun 28', done:false },
    ],
    createdAt: new Date(Date.now() - 2*3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1*3600000).toISOString(),
  },
  {
    id: 'issue_002',
    title: 'Water Main Burst — Road Flooding at Gandhipuram Junction',
    description: 'Municipal pipe burst causing severe waterlogging at the main junction. Traffic at a standstill. Risk of electrical short-circuit with exposed cables nearby.',
    category: 'water',
    categoryLabel: 'Water & Drainage',
    severity: 'critical',
    status: 'in_progress',
    votes: 89,
    verifications: 5,
    userVoted: null,
    userVerified: false,
    emoji: '💧',
    location: {
      lat: 11.0168, lng: 76.9558,
      address: 'Gandhipuram Junction, Coimbatore',
      ward: 'Ward 4',
      zone: 'Central Zone',
    },
    reporter: { id:'user_003', name:'Priya Venkat', initials:'PV', level:10 },
    assignedDept: 'TWAD Board',
    workOrder: 'TWAD-2024-0412',
    aiAnalysis: {
      category: 'water',
      severity: 'critical',
      confidence: 0.91,
      tags: ['Water Leak','Flooding Risk','Infrastructure','Electrical Hazard'],
      estimatedCost: 45000,
      similarIssues: 4,
    },
    images: [],
    comments: [],
    timeline: [
      { status:'Reported', time:'Jun 22, 6:30 AM', done:true },
      { status:'AI Verified', time:'Jun 22, 6:31 AM', done:true },
      { status:'Escalated — Critical', time:'Jun 22, 7:00 AM', done:true },
      { status:'TWAD Team Dispatched', time:'Jun 22, 8:45 AM', done:true },
      { status:'In Progress', time:'Jun 22, 10:00 AM', done:false },
    ],
    createdAt: new Date(Date.now() - 4*3600000).toISOString(),
    updatedAt: new Date(Date.now() - 30*60000).toISOString(),
  },
  {
    id: 'issue_003',
    title: '14 Consecutive Streetlights Out — Saibaba Colony Main Road',
    description: 'Entire stretch of Saibaba Colony main road is pitch dark from 7 PM onwards. Women and elderly residents are scared to walk. Reported to TANGEDCO twice with no action.',
    category: 'electricity',
    categoryLabel: 'Electricity',
    severity: 'high',
    status: 'verified',
    votes: 62,
    verifications: 12,
    userVoted: null,
    userVerified: false,
    emoji: '⚡',
    location: {
      lat: 11.0168, lng: 77.0122,
      address: 'Saibaba Colony Main Road, Coimbatore',
      ward: 'Ward 18',
      zone: 'West Zone',
    },
    reporter: { id:'user_004', name:'Muthu Selvam', initials:'MS', level:9 },
    assignedDept: 'TANGEDCO',
    workOrder: 'TNEB-2024-1103',
    aiAnalysis: {
      category: 'electricity',
      severity: 'high',
      confidence: 0.88,
      tags: ['Electrical','Night Safety','Multiple Failures','Recurring Pattern'],
      estimatedCost: 12000,
      similarIssues: 2,
    },
    images: [],
    comments: [
      { id:'c3', user:'Kavitha R.', text:'This has been happening for 3 weeks!', time:'2h ago' },
    ],
    timeline: [
      { status:'Reported', time:'Jun 21, 8:00 PM', done:true },
      { status:'AI Verified', time:'Jun 21, 8:01 PM', done:true },
      { status:'Pattern Detected', time:'Jun 21, 8:01 PM', done:true, note:'AI: Recurring 18-day cycle' },
      { status:'Assigned to TANGEDCO', time:'Jun 22, 9:00 AM', done:true },
      { status:'Resolution Pending', time:'ETA: Jun 25', done:false },
    ],
    createdAt: new Date(Date.now() - 6*3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2*3600000).toISOString(),
  },
  {
    id: 'issue_004',
    title: 'Overflowing Garbage — Saibaba Colony Market',
    description: 'Bin overflowing for 4 days. Stray dogs spreading waste across 200m radius. Severe stench. Health hazard for nearby school.',
    category: 'waste',
    categoryLabel: 'Waste Management',
    severity: 'medium',
    status: 'resolved',
    votes: 43,
    verifications: 7,
    userVoted: 'up',
    userVerified: false,
    emoji: '🗑️',
    location: {
      lat: 11.0268, lng: 76.9658,
      address: 'Saibaba Colony Market, Coimbatore',
      ward: 'Ward 16',
      zone: 'West Zone',
    },
    reporter: { id:'user_005', name:'Kavitha Raj', initials:'KR', level:7 },
    assignedDept: 'Solid Waste Management',
    workOrder: 'SWM-2024-5521',
    aiAnalysis: {
      category: 'waste',
      severity: 'medium',
      confidence: 0.86,
      tags: ['Garbage','Hygiene Risk','Stray Animals','School Proximity'],
      estimatedCost: 2000,
      similarIssues: 1,
    },
    images: [],
    comments: [],
    timeline: [
      { status:'Reported', time:'Jun 20, 9:00 AM', done:true },
      { status:'AI Verified', time:'Jun 20, 9:01 AM', done:true },
      { status:'Assigned', time:'Jun 20, 10:00 AM', done:true },
      { status:'Resolved ✓', time:'Jun 21, 2:00 PM', done:true, note:'Area cleaned, schedule updated' },
    ],
    createdAt: new Date(Date.now() - 24*3600000).toISOString(),
    updatedAt: new Date(Date.now() - 16*3600000).toISOString(),
  },
  {
    id: 'issue_005',
    title: 'Large Tree Fell Across Dr. Nanjappa Road — 2 Lanes Blocked',
    description: 'Old rain tree fell blocking entire northbound lanes. Emergency vehicles cannot pass. Power lines may be damaged. Need immediate clearing.',
    category: 'tree',
    categoryLabel: 'Obstruction',
    severity: 'critical',
    status: 'pending',
    votes: 201,
    verifications: 15,
    userVoted: null,
    userVerified: false,
    emoji: '🌳',
    location: {
      lat: 11.0318, lng: 77.0182,
      address: 'Dr. Nanjappa Road, Coimbatore',
      ward: 'Ward 8',
      zone: 'Central Zone',
    },
    reporter: { id:'user_006', name:'Ravi Subramanian', initials:'RS', level:6 },
    assignedDept: null,
    workOrder: null,
    aiAnalysis: {
      category: 'tree',
      severity: 'critical',
      confidence: 0.97,
      tags: ['Tree Fall','Road Block','Emergency','Power Line Risk'],
      estimatedCost: 15000,
      similarIssues: 0,
    },
    images: [],
    comments: [],
    timeline: [
      { status:'Reported', time:'30 min ago', done:true },
      { status:'AI Verified — CRITICAL', time:'30 min ago', done:true },
      { status:'Auto-Escalated', time:'28 min ago', done:true, note:'Emergency services notified' },
      { status:'Awaiting Assignment', time:'Pending', done:false },
    ],
    createdAt: new Date(Date.now() - 30*60000).toISOString(),
    updatedAt: new Date(Date.now() - 25*60000).toISOString(),
  },
  {
    id: 'issue_006',
    title: 'Storm Drain Overflow into Homes — Peelamedu Colony',
    description: 'Storm drain backing up into 6 ground-floor homes after yesterday\'s rain. Sewage mixed water entering living areas. Families with children affected.',
    category: 'drainage',
    categoryLabel: 'Drainage',
    severity: 'high',
    status: 'verified',
    votes: 77,
    verifications: 4,
    userVoted: null,
    userVerified: false,
    emoji: '🌊',
    location: {
      lat: 11.0418, lng: 77.0382,
      address: 'Peelamedu Residential Colony, Coimbatore',
      ward: 'Ward 24',
      zone: 'East Zone',
    },
    reporter: { id:'user_007', name:'Meena Thangavel', initials:'MT', level:8 },
    assignedDept: 'Storm Water Drain Dept.',
    workOrder: 'SWD-2024-0887',
    aiAnalysis: {
      category: 'drainage',
      severity: 'high',
      confidence: 0.89,
      tags: ['Drainage','Flooding','Residential','Health Hazard'],
      estimatedCost: 25000,
      similarIssues: 2,
    },
    images: [],
    comments: [],
    timeline: [
      { status:'Reported', time:'Jun 22, 3:00 AM', done:true },
      { status:'AI Verified', time:'Jun 22, 3:01 AM', done:true },
      { status:'Community Validated', time:'Jun 22, 6:00 AM', done:true },
      { status:'Assigned — SWD', time:'Jun 22, 9:00 AM', done:true },
      { status:'Resolution Pending', time:'ETA: Jun 27', done:false },
    ],
    createdAt: new Date(Date.now() - 3*3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1*3600000).toISOString(),
  },
]

// ─── Mock Predictions ─────────────────────────────────────────────────────────
export const MOCK_PREDICTIONS = [
  {
    id:'pred_001', probability:0.87, category:'pothole', severity:'high',
    title:'Pothole surge on NH-44 after rain forecast',
    zone:'NH-44, Singanallur stretch',
    trigger:'IMD: 12mm rain predicted Friday',
    timeframe:'Next 3 days',
    recommendation:'Pre-emptive pothole patching on 2.3km stretch',
    estimatedIssues:14, estimatedCost:45000, costSaved:120000,
    modelConfidence:0.87, source:'IMD + 6-month historical data',
  },
  {
    id:'pred_002', probability:0.72, category:'drainage', severity:'high',
    title:'Waterlogging in Gandhipuram during monsoon peak',
    zone:'Gandhipuram, Nehru Street area',
    trigger:'Monsoon onset + blocked drain history',
    timeframe:'Next 5 days',
    recommendation:'Clear 3 storm drains pre-emptively',
    estimatedIssues:8, estimatedCost:12000, costSaved:65000,
    modelConfidence:0.72, source:'Historical flood data + Weather forecast',
  },
  {
    id:'pred_003', probability:0.61, category:'electricity', severity:'medium',
    title:'Streetlight failures in R.S. Puram sector',
    zone:'R.S. Puram, 5th–9th Streets',
    trigger:'18-day recurring failure cycle detected',
    timeframe:'Next 4 days',
    recommendation:'Auto-schedule TANGEDCO maintenance',
    estimatedIssues:12, estimatedCost:8000, costSaved:22000,
    modelConfidence:0.61, source:'Pattern recognition · 6 previous occurrences',
  },
  {
    id:'pred_004', probability:0.44, category:'waste', severity:'medium',
    title:'Garbage overflow near Saibaba Colony market',
    zone:'Saibaba Colony, market area',
    trigger:'Festival week + collection gap detected',
    timeframe:'Next 7 days',
    recommendation:'Add extra collection run Thursday',
    estimatedIssues:5, estimatedCost:3000, costSaved:8000,
    modelConfidence:0.44, source:'Festival calendar + collection schedule analysis',
  },
]

// ─── Mock Feed ────────────────────────────────────────────────────────────────
export const MOCK_FEED = [
  {
    id:'feed_001', type:'report',
    user:{ name:'Rajesh Kumar', initials:'RK', color:'#f59e0b', level:15 },
    time:'5m ago', timeRaw: new Date(Date.now() - 5*60000),
    text:'Just reported a massive pothole near Ganesh Theatre. AI classified it Critical — 94% confidence. Stay safe everyone! 🚨',
    linkedIssue:{ id:'issue_001', title:'Deep Pothole — Avinashi Road', severity:'critical' },
    reactions:{ support:23, verify:8, share:5 }, userReacted:null,
    tags:['#PotholeAlert','#AvinashiRoad'],
  },
  {
    id:'feed_002', type:'ai_alert',
    user:{ name:'CivicPulse AI', initials:'🤖', color:'#7c3aed', level:99 },
    time:'12m ago', timeRaw: new Date(Date.now() - 12*60000),
    text:'🔔 ALERT: 4 reports in the last hour near Gandhipuram Junction all point to a water main burst. Auto-merging reports and escalating to Coimbatore Municipal Corporation. Work order #CMC-2024-0091 created automatically.',
    linkedIssue:{ id:'issue_002', title:'Water Main Burst — Gandhipuram', severity:'critical' },
    reactions:{ support:41, verify:0, share:18 }, userReacted:null,
    tags:['#AutoEscalated','#WaterCrisis'],
  },
  {
    id:'feed_003', type:'verification',
    user:{ name:'Priya Venkat', initials:'PV', color:'#4f46e5', level:10 },
    time:'28m ago', timeRaw: new Date(Date.now() - 28*60000),
    text:'✅ Just verified the streetlight report on Saibaba Colony 2nd street — confirmed! Already dark for a week. Please upvote so TANGEDCO responds faster! 🌑',
    linkedIssue:{ id:'issue_003', title:'Streetlights Out — Saibaba Colony', severity:'high' },
    reactions:{ support:15, verify:3, share:7 }, userReacted:null,
    tags:['#NightSafety','#TANGEDCO'],
  },
  {
    id:'feed_004', type:'resolution',
    user:{ name:'Municipal Corp CBE', initials:'🏛️', color:'#059669', level:0 },
    time:'1h ago', timeRaw: new Date(Date.now() - 3600000),
    text:'✅ RESOLVED: Garbage overflow near Saibaba market (Report #1847) has been cleared. Big thank you to Kavitha R. for the detailed, photo-documented report. We are now scheduling twice-weekly collection for this area.',
    linkedIssue:null,
    reactions:{ support:67, verify:0, share:22 }, userReacted:null,
    tags:['#Resolved','#CleanCBE'],
  },
  {
    id:'feed_005', type:'tip',
    user:{ name:'Muthu Selvam', initials:'MS', color:'#0d9488', level:9 },
    time:'2h ago', timeRaw: new Date(Date.now() - 7200000),
    text:'💡 Monsoon prep tip: Clear your terrace drains NOW before the rain hits Friday. I use CivicPulse to report any blocked drains before they become flooding problems. 7 reports filed this week already! 💪 The AI predicted waterlogging in our area — let\'s beat it proactively.',
    linkedIssue:null,
    reactions:{ support:31, verify:0, share:14 }, userReacted:null,
    tags:['#MonsoonPrep','#ProTip'],
  },
  {
    id:'feed_006', type:'badge',
    user:{ name:'Arjun Kumar', initials:'AK', color:'#1a56db', level:12 },
    time:'3h ago', timeRaw: new Date(Date.now() - 10800000),
    text:'🏅 Just earned the "Monsoon Watch" badge for reporting 5 drainage issues this season! Every report makes a difference. Together we\'re building a more responsive city. Keep reporting, neighbors! 🌧️',
    linkedIssue:null,
    reactions:{ support:44, verify:0, share:9 }, userReacted:null,
    tags:['#MonsoonWatch','#CivicHero'],
  },
]

// ─── Mock Leaderboard ─────────────────────────────────────────────────────────
export const MOCK_LEADERBOARD = [
  { rank:1,  id:'user_ldr_1',  name:'Rajesh Kumar',    initials:'RK', color:'#f59e0b', xp:4200, level:15, title:'Urban Guardian',    reports:187, badges:['👑','🌟','⚡'], city:'Coimbatore' },
  { rank:2,  id:'user_ldr_2',  name:'Priya Venkat',    initials:'PV', color:'#4f46e5', xp:3850, level:14, title:'Road Warrior',      reports:162, badges:['🏆','⚡','📸'], city:'Coimbatore' },
  { rank:3,  id:'user_ldr_3',  name:'Muthu Selvam',    initials:'MS', color:'#0d9488', xp:3420, level:13, title:'Water Champion',    reports:144, badges:['💧','🔍','🌧️'], city:'Coimbatore' },
  { rank:4,  id:'user_ldr_4',  name:'Kavitha Raj',     initials:'KR', color:'#dc2626', xp:3100, level:12, title:'Night Watcher',     reports:131, badges:['🌙','🏅'], city:'Coimbatore' },
  { rank:5,  id:'user_ldr_5',  name:'Suresh T.',       initials:'ST', color:'#0ea5e9', xp:2920, level:11, title:'Eco Warrior',       reports:118, badges:['♻️','🌿'], city:'Coimbatore' },
  { rank:6,  id:'user_ldr_6',  name:'Anitha Moorthy',  initials:'AM', color:'#8b5cf6', xp:2840, level:11, title:'Drain Detective',   reports:112, badges:['🌊','🔍'], city:'Coimbatore' },
  { rank:7,  id:'user_ldr_7',  name:'Balamurugan K.',  initials:'BK', color:'#ec4899', xp:2710, level:10, title:'Street Sentinel',   reports:108, badges:['👁️','🏅'], city:'Coimbatore' },
  { rank:8,  id:'user_ldr_8',  name:'Deepa Rajan',     initials:'DR', color:'#f97316', xp:2540, level:10, title:'Safety First',      reports:99,  badges:['🚨','⚠️'], city:'Coimbatore' },
  { rank:9,  id:'user_ldr_9',  name:'Ganesan V.',      initials:'GV', color:'#14b8a6', xp:2380, level:9,  title:'Tree Guardian',     reports:94,  badges:['🌳','🌿'], city:'Coimbatore' },
  { rank:10, id:'user_ldr_10', name:'Hema Shankar',    initials:'HS', color:'#6366f1', xp:2210, level:9,  title:'Pothole Patrol',    reports:88,  badges:['🕳️','🛣️'], city:'Coimbatore' },
  { rank:11, id:'user_ldr_11', name:'Ilayaraja M.',    initials:'IM', color:'#84cc16', xp:2050, level:9,  title:'Civic Volunteer',   reports:82,  badges:['🤝','📸'], city:'Coimbatore' },
  { rank:12, id:'user_001',    name:'Arjun Kumar',     initials:'AK', color:'#1a56db', xp:2840, level:12, title:'Civic Champion',    reports:143, badges:['🏅','📸','⚡'], city:'Coimbatore', isCurrentUser:true },
]

// ─── Mock Dashboard Stats ─────────────────────────────────────────────────────
export const MOCK_STATS = {
  openThisWeek: 247,
  openDelta: 14,
  resolvedThisWeek: 182,
  resolvedDelta: 23,
  avgResolutionHours: 18,
  avgResolutionDelta: -34,
  activeReportersToday: 1284,
  activeReportersDelta: 8,
  totalReported: 12847,
  totalResolved: 9241,
  totalCitizens: 34521,
  moneySaved: 28000000,
  resolutionRate: 71.8,
  cityHealthScore: 94,
}

export const MOCK_WEEKLY = {
  labels: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
  reported: [42, 38, 55, 47, 61, 28, 22],
  resolved:  [35, 29, 48, 39, 54, 22, 18],
}

export const MOCK_CATEGORIES = {
  labels: ['Potholes','Water','Electricity','Waste','Drainage','Other'],
  data:   [34, 22, 18, 14, 8, 4],
  colors: ['#dc2626','#1a56db','#f59e0b','#059669','#7c3aed','#94a3b8'],
}

export const MOCK_MONTHLY = {
  labels: ['Jan','Feb','Mar','Apr','May','Jun'],
  reported: [120, 145, 132, 178, 210, 247],
  resolved:  [98,  119, 121, 155, 188, 182],
}

export const MOCK_DEPARTMENTS = [
  { name:'Roads & PWD',      hours:24, pct:80,  color:'#1a56db', issues:89 },
  { name:'Water Works',      hours:18, pct:60,  color:'#7c3aed', issues:56 },
  { name:'TANGEDCO',         hours:12, pct:40,  color:'#f59e0b', issues:44 },
  { name:'Solid Waste Mgmt', hours:28, pct:93,  color:'#d97706', issues:34 },
  { name:'Storm Water Drain',hours:30, pct:100, color:'#dc2626', issues:19 },
  { name:'Parks & Trees',    hours:36, pct:100, color:'#059669', issues:11 },
]

// ─── Badge definitions ────────────────────────────────────────────────────────
export const BADGE_DEFS = [
  { id:'first_responder', emoji:'🔍', name:'First Responder',  desc:'Report within 10 min of an issue occurring',    earned:true  },
  { id:'photo_pro',       emoji:'📸', name:'Photo Pro',         desc:'10 photo reports with AI confidence >90%',      earned:true  },
  { id:'speed_reporter',  emoji:'⚡', name:'Speed Reporter',    desc:'5 issues reported in under 1 minute each',      earned:true  },
  { id:'monsoon_watch',   emoji:'🌧️', name:'Monsoon Watch',    desc:'Report 5 drainage issues during monsoon',       earned:true  },
  { id:'validator',       emoji:'🤝', name:'Validator',         desc:'Verify 25 issues reported by others',           earned:true  },
  { id:'top10_weekly',    emoji:'🏆', name:'Top 10 Weekly',    desc:'Reach top 10 on weekly leaderboard',            earned:true  },
  { id:'city_hero',       emoji:'👑', name:'City Hero',         desc:'Report 500 issues (${143}/500)',                earned:false },
  { id:'thousand_club',   emoji:'🌟', name:'1000 Reports',     desc:'Report 1000 issues total',                      earned:false },
]

// ─── Activity heatmap generator ───────────────────────────────────────────────
export function generateActivityData() {
  const cells = []
  for (let i = 0; i < 52 * 7; i++) {
    const r = Math.random()
    let level = 0
    if (r > 0.85) level = 4
    else if (r > 0.70) level = 3
    else if (r > 0.55) level = 2
    else if (r > 0.40) level = 1
    cells.push(level)
  }
  return cells
}
